# SwiftLint config - strict rules to catch LLM mistakes

included:
  - app
  - Tests

excluded:
  - .build

# Rules that catch common LLM mistakes
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - shorthand_optional_binding
  - sorted_first_last
  - toggle_bool
  - trailing_comma
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - yoda_condition

# Disable noisy/SwiftUI-incompatible rules
disabled_rules:
  - trailing_whitespace
  - todo
  - opening_brace
  - identifier_name
  - type_name
  - nesting
  - large_tuple
  - cyclomatic_complexity
  - notification_center_detachment
  - multiple_closures_with_trailing_closure  # normal in SwiftUI
  - implicit_optional_initialization         # @State var x: T? = nil is fine
  - implicitly_unwrapped_optional            # needed for AppKit interop
  - multiline_arguments                      # too strict for SwiftUI DSL
  - multiline_parameters                     # too strict for SwiftUI DSL
  - redundant_discardable_let                # let _ = is sometimes clearer
  - for_where                                # sometimes if-in-for is clearer
  - statement_position                       # style preference

# Thresholds
line_length:
  warning: 200
  error: 300

file_length:
  warning: 1000
  error: 1500

type_body_length:
  warning: 700
  error: 1000

function_body_length:
  warning: 150
  error: 250

function_parameter_count:
  warning: 8
  error: 12

# Force unwrap is the #1 LLM mistake
force_cast:
  severity: error

force_unwrapping:
  severity: warning

force_try:
  severity: warning
